<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>WarehouseRefillPlus</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>AnyCPU</Platforms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PackageId>WarehouseRefillPlus</PackageId>
    <Version>3.2.0</Version>
    <AssemblyVersion>3.2.0</AssemblyVersion>
    <FileVersion>3.2.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\Debug\</OutputPath>
    <Optimize>false</Optimize>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>bin\Release\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\interop\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\core\BepInEx.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\interop\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\interop\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\Desktop 2\Nowa instancja SS\BepInEx\interop\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\refill_icon.png" />
    <EmbeddedResource Include="Resources\reset_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TabletDevice_OnAddItem_Patch.cs" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;$(TargetPath)&quot; &quot;C:\Users\tmjci\Desktop 2\Nowa instancja SS\BepInEx\plugins&quot;" />
  </Target>
</Project>